name: ci

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: restore
        run: dotnet restore
      - name: build
        run: dotnet build -c Release --no-restore
      - name: test
        run: dotnet test
      - name: publish
        run: dotnet publish src/Anvil.Server -c Release -o publish /p AssemblyName=anvil-server

      - uses: actions/upload-artifact@v4
        with:
          name: application
          path: publish/anvil-server
